# Generated by Django 3.1.3 on 2020-12-27 19:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('catid', models.IntegerField(db_column='catID', primary_key=True, serialize=False)),
                ('name', models.TextField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'Category',
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('custid', models.AutoField(db_column='custID', primary_key=True, serialize=False)),
                ('name', models.TextField(blank=True, max_length=100, null=True)),
                ('contact', models.TextField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'Customer',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('orderid', models.AutoField(db_column='orderID', primary_key=True, serialize=False)),
                ('date', models.DateField(blank=True, null=True)),
                ('custid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.customer')),
            ],
            options={
                'db_table': 'Order',
            },
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('supid', models.AutoField(db_column='supID', primary_key=True, serialize=False)),
                ('name', models.TextField(blank=True, max_length=100, null=True)),
                ('contact', models.TextField(blank=True, max_length=100, null=True)),
                ('catid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.category')),
            ],
            options={
                'db_table': 'Supplier',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('prodid', models.AutoField(db_column='prodID', primary_key=True, serialize=False)),
                ('name', models.TextField(blank=True, max_length=100, null=True)),
                ('unitprice', models.IntegerField(blank=True, db_column='unitPrice', null=True)),
                ('instock', models.IntegerField(blank=True, db_column='inStock', null=True)),
                ('catid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.category')),
            ],
            options={
                'db_table': 'Product',
            },
        ),
        migrations.CreateModel(
            name='OrderDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.IntegerField(blank=True, null=True)),
                ('orderid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.order')),
                ('prodid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.product')),
            ],
            options={
                'db_table': 'Order-Details',
            },
        ),
    ]
