# Generated by Django 3.1.3 on 2020-12-31 07:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='desc',
            field=models.TextField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(default='0', upload_to='shop/images'),
        ),
        migrations.AlterField(
            model_name='order',
            name='custid',
            field=models.ForeignKey(db_column='custID', on_delete=django.db.models.deletion.CASCADE, to='shop.customer'),
        ),
        migrations.AlterField(
            model_name='orderdetails',
            name='id',
            field=models.AutoField(db_column='ID', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='orderdetails',
            name='orderid',
            field=models.ForeignKey(db_column='orderID', on_delete=django.db.models.deletion.CASCADE, to='shop.order'),
        ),
        migrations.AlterField(
            model_name='orderdetails',
            name='prodid',
            field=models.ForeignKey(db_column='prodID', on_delete=django.db.models.deletion.CASCADE, to='shop.product'),
        ),
        migrations.AlterField(
            model_name='product',
            name='catid',
            field=models.ForeignKey(db_column='catID', on_delete=django.db.models.deletion.CASCADE, to='shop.category'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='catid',
            field=models.ForeignKey(db_column='catID', on_delete=django.db.models.deletion.CASCADE, to='shop.category'),
        ),
    ]
